# Generated by Django 6.1 on 2026-08-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdate',
            name='votes_count',
        ),
    ]
